version: '3.8'

services:

  db:

    image: mongo:6.0.6

    restart: always

    environment:

      MONGODB_DATABASE: nest-pokemon

    volumes:

      - ./mongo:/data/db

    ports:

      - 27017:27017